import "~/styles/globals.css";
import BackgroundCanvas from "./_components/background-canvas";
import Navbar from "./_components/navbar";

import { type Metadata } from "next";
import { Geist } from "next/font/google";

import { TRPCReactProvider } from "~/trpc/react";
import { SessionProvider } from "next-auth/react";
import { auth } from "~/server/auth";

export const metadata: Metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

const geist = Geist({
  subsets: ["latin"],
});

export default async function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  
  const session = await auth();

  return (
    <html lang="en">
      <body className={geist.className}>
        <SessionProvider  session={session}>
          <TRPCReactProvider>
            <BackgroundCanvas />
            <Navbar />
            {children}
          </TRPCReactProvider>
        </SessionProvider>
      </body>
    </html>
  );
}
